title: Yadu's blog
author: Yaduveer Singh
email: ysingh@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  This is my blog. I'll update regularly
  
# social links
twitter_username: yadusingh
github_username:  ysinghebnet

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
